# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\"\x1c\n\tMyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nMyResponse\x12\x0f\n\x07message\x18\x02 \x01(\t22\n\tMyService\x12%\n\x08MyMethod\x12\n.MyRequest\x1a\x0b.MyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYREQUEST']._serialized_start=20
  _globals['_MYREQUEST']._serialized_end=48
  _globals['_MYRESPONSE']._serialized_start=50
  _globals['_MYRESPONSE']._serialized_end=79
  _globals['_MYSERVICE']._serialized_start=81
  _globals['_MYSERVICE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
